### ISSUE TITLE
A problem about the NS3 project

### ISSUE THREAD

**Issue by lingyuhaunti** [FujiZ/ns-3#2]
Excuse me，I want to know your "m_ecnState“ in dctcp-soket.cc. The value maybe always equal 0,that mean the protocol is not ecn awareness. thank you very much。

**Comment by FujiZ** [comment]
Thanks for your feedback. m_ecnState is a combination state of TcpSocket::EcnStates_t, this value is changed mainly in TcpSocketBase class. If you want to enable ECN in TcpSocket, try to set the attribute "UseEcn" of TcpSocketBase to true.

**Comment by lingyuhaunti** [comment]
Thank you for your answer.In fact,I just start learning the NS3 ,and don't know the NS3 working principle，and also want to know when the simulator is running,how to excute the function that you defined.
My email :1307030220@s.upc.edu.cn   if possible we can contact ench other by email.

**Comment by FujiZ** [comment]
I'd be glad to lend a hand, just contact me by email.
