### ISSUE TITLE
Some questions about Dctcp project

### ISSUE THREAD

**Issue by hdtjiang** [FujiZ/ns-3#3]
Hello，
 I have ran the codes about Dctcp，but i found that the function DecreaseWindow( )  in  dctcpsocket & tcp-socket-base has never used . Then I want to know how to realize the Dctcp about the m_Cwd.

The second questions is about the differences between the server and the switch .

The third is about the traffic .You changed the app start time and stop time in different nodes .What is the traffic module.

Thanks a lot

**Comment by FujiZ** [comment]
Thanks for your feedback.

- If you want to use dctcp, be sure to enable the attribute "UseEcn" in TcpSocketBase. DecreaseWindow() is called in SendPendingData() before sending next window of data. This implementation refers to [i-maravic/ns-3](https://github.com/i-maravic/ns-3), but in the latest version.
- Servers run Applications (aka L5Protocol) while switches do not.
- If you mean the dctcp-convergence-test in scratch, it's a test to verify the convergence performance of dctcp comparing to the original paper, you can find the detail info about the test there.

Later I will update a new version of this repo, in which empty packets and retransmit packets will be marked ECT in DCTCP, it should reduce the possibility of dropping these kinds of packets.

**Comment by hdtjiang** [comment]
Thanks for your answer.
I tried to output the m_cWnd & m _ssThresh in DecreaseWindow( ); But it may have something wrong with it .The first output is 103864&103864 .It's OK. But the second output changed to a very large number 112406168. The later is OK.
And sometimes when i simulate , even though i open the useEcn , the window and the ssTh are very large. 
And I cannot find what i ignored. 
Thanks.

**Comment by FujiZ** [comment]
Sorry for replaying so late.
Currently I'm looking into the cwnd problem. When I test L2DCT, it seems that the cwnd is growing without any limitations, thus make the congestion control ineffective. I'm turning to my labmates for help. I will contact you if there is any progress.

**Comment by FujiZ** [comment]
Hi Jiang, I just pushed a new commit in which the formula of DCTCP is cwnd=(1-alpha/2)*window() instead of cwnd=(1-alpha/2)*cwnd. This will reduce the effects of very large cwnd when there is only one flow in the network. 
However, I think the unlimited growth of cwnd is a bug in ns-3. It will cause overflow of cwnd every 75s in my test. Maybe adding a upper bound to cwnd is a solution to this problem.
