### ISSUE TITLE
where the SetInitialSSThresh (uint32_t threshold) is excuted

### ISSUE THREAD

**Issue by lingyuhaunti** [FujiZ/ns-3#4]
Excuse me,when I tested the dctcp program ,I founded the function the initial m_tcb->m_ssThresh's value is (2^32)-1 ,but I can't founded where the SetInitialSSThresh (uint32_t threshold) is excuted.,and can't understand why the  m_tcb->m_ssThresh's value is UINT32_MAX.
Thank you.

**Comment by FujiZ** [comment]
According to [RFC 5681](https://tools.ietf.org/html/rfc5681):

>   The initial value of ssthresh SHOULD be set arbitrarily high (e.g., to the size of the largest possible advertised window), but ssthresh MUST be reduced in response to congestion. 

SsThresh is initialized in DoForwardUp () when it received a SYN packet.
The initialSsThresh is an attribute of TcpSocket, you can find the default value there.
