### ISSUE TITLE
Some questions about DCTCP

### ISSUE THREAD

**Issue by hdtjiang** [FujiZ/ns-3#8]
Thanks for your answer。
And you have changed the attribute "Limit" in pfifofastqueuedisc from 100 to 1000.Thus the codes cannot run because the queue limit in queue.cc is only 100.
The second problem is that the server can send back ECN .But the client cannot match the conditions into DecreaseWindow( );

**Comment by FujiZ** [comment]
The default value of "Limit" in pfifo queue is 1000, if you want to change the queue size of queue disc, you should change both the root queue disc and the internal queue. I just change the queue size in dctcp-test in the latest commit.
DCTCP cut it's window size at most once for every window. DecreaseWindow () is called before sending next window of data. You can run dctcp-test to test the convergence performance of DCTCP. Remember to specify the args of the test.

**Comment by hdtjiang** [comment]
Hello，i has found a new question and cannot solve it. So i want to get some suggestions from you.
my "data_rate" is 10Gbps or 40Gbps. It's really fast and i found that large amount of packets are missing.I tested the on-off app and the app generated the correct number of packets and sent correctly.But the test in p2p-netdevice or in the red-queue of sender shows that it has missing over 80% packets. I wanna where i can modify to solve this problem. 
Thanks a lot .

**Comment by FujiZ** [comment]
Hi Jiang. You know that the net-device also contains a queue. The default length for the queue is 100. When you try a higher data rate, you may adjust the length of net-device queue  as well. The attribute "TxQueue" in p2p-net-device may help you with this problem.

**Comment by hdtjiang** [comment]
Thanks for your reply.
I had found the parameter in tcp-socket.cc and the SndBufSize is too small.
Thanks a lot.

**Comment by hdtjiang** [comment]
Hello。
If we change the number of SndBufSize ，there is another problem that the utilization rate of memory is too high and the simulation is hard to close.
So we can change the SendPacket() in on-off-application.cc. if the packet send event failed ,we cannot add pktsize to totsize. That's enough to solve the problem.

**Comment by FujiZ** [comment]
I think it may not be a perfect solution but it is enough for a simulation. Thanks for your feedback!
